name: Builder
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: 1.24
      - name: Install dependencies
        run: go get .
      - name: Build arm64
        env:
          GOARCH: arm64
        run: go build -o linux-arm64 .
      - name: Upload built binary
        uses: actions/upload-artifact@v4
        with:
          path: linux-arm64
